export const actions = {
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  CLOSE_TODO: "CLOSE_TODO",
  FILTER_TODOS: "FILTER_TODOS",
  SORT_TODOS: "SORT_TODOS",
  SEARCH_TODOS: "SEARCH_TODOS",
};
